functionality:
  name: submission_171123
  namespace: predict_modality_methods
  
  # metadata for your method
  description: A description for your method.
  info:
    submission_id: "171123"
    team_name: LS_lab
    # project_url: https://github.com/foo/bar
    # publication_doi: 10.1101/0123.45.67.890123
    # publication_url: https://arxiv.org/abs/1234.56789

  authors:
    - name: John Doe
      email: johndoe@youremailprovider.com
      roles: [ author, maintainer ]
      props: { github: johndoe, orcid: "0000-1111-2222-3333" }
      
  # parameters
  arguments:
    # required inputs
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, training cells.
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset, test cells.
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    # required outputs
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
      
  # files your script needs
  resources:
    - type: python_script
      path: script.py
      
# target platforms
platforms:
  - type: docker
    image: pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
    run_args: [ "--gpus all" ]
    setup:
      - type: python
        packages:
          - scikit-learn
          - catboost
          - anndata
          - scanpy
          - tqdm
  - type: nextflow
    labels: [ vhighmem, vvhightime, highcpu, gpu]
